### ISSUE TITLE
Add Mastodon support

### ISSUE THREAD

**Issue by thisisparker** [freedomofpress/trackthenews#11]
It's probably sufficient to allow Mastodon tooting through manually adding credentials to the `config.yaml` file, so this should be pretty straightforward.

**Comment by eloquence** [comment]
We'll want to prioritize this given the uncertainty about Twitter's APIs and its future in general. I've requested a foiafeed@ account on the botsin.space instance for now, will update this ticket once approved or rejected.

**Comment by creviera** [comment]
Per Web Sync: We want to prioritize this so we can use it for the FOIAFeed. @harrislapiroff and @eloquence have offered to work on a Mastodon bot and whatever else is needed as next steps.

**Comment by harrislapiroff** [comment]
https://botsin.space/@FOIAFeed
