### ISSUE TITLE
Twitter API returned a 400 (Bad Request), Tweet must not have more than 4 mediaIds.

### ISSUE THREAD

**Issue by jfilter** [freedomofpress/trackthenews#20]
I don't know if Twitter changed it but I can't post more than 4 images right now. I receive the following error message:

```
Twitter API returned a 400 (Bad Request), Tweet must not have more than 4 mediaIds.
```

**Comment by thisisparker** [comment]
Hm, it's always been four but TTN should only be rendering the first 4 matches. (That's here: https://github.com/freedomofpress/trackthenews/blob/master/trackthenews/core.py#L94-L95). Are you running a version with those lines intact?

**Comment by jfilter** [comment]
Oh yeah, I have those lines. I don't know where the error came from. But it works now.
