### ISSUE TITLE
Unbreak Twitter bot

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/trackthenews#38]
FOIAFeed is currently unable to post due to Twitter "deprecating" (in fact, breaking) access to their old API.
> The v1.1 APIs have been deprecated and your app is no longer able to access those v1.1 APIs. Please create a new application using one of our v2 Free, Basic or Pro plans today!

Let's see if we can migrate to the new API at reasonable cost.

**Comment by eloquence** [comment]
#41 should fix this, but will keep open until it is deployed.

**Comment by harrislapiroff** [comment]
Resolved
