### ISSUE TITLE
Release new version on PyPI

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/trackthenews#42]
Once we've got Mastodon support landed as well, we should release a new version on PyPI.

**Comment by harrislapiroff** [comment]
We released `0.1.11` with Twitter v2 API support, but I'll leave this open till we issue a release with mastodon support

**Comment by eloquence** [comment]
@harrislapiroff I think we can bump the version now, Pillow upgrade probably will benefit from a bit more time in review

**Comment by harrislapiroff** [comment]
I think this deserves a 0.2 release

**Comment by harrislapiroff** [comment]
[Released!](https://pypi.org/project/trackthenews/0.2/)
