### ISSUE TITLE
Document the purpose of 'delicateURLs' and 'redirectLinks' in rssfeeds.json

### ISSUE THREAD

**Issue by Cauchon** [freedomofpress/trackthenews#5]
It's unclear what delicateURLs and redirectLinks do in the RSS Feeds JSON file. In the example, some are true and some are false, but it's unclear why.

Could we get documentation on what these values mean?

**Comment by thisisparker** [comment]
Oh thank you, that is good feedback and I will add it to the documentation tomorrow. The short version is, they're optional so if things run fine without them, don't sweat it. The only slightly longer version is:
- If `redirectLinks` is set to `true`, the script will assume that the feed uses non-canonical links and so it will attempt to follow them with a HEAD request to get the "true" link. One example from the sample file is [the ProPublica feed](http://feeds.propublica.org/propublica/main), where all the URLs are to `feedpress.it`, and we want the actual `propublica.org` URLs.
- If `delicateURLs` is set to `true`, the script will skip some standard URL "cleanup" steps that involve snipping off domain hash and query strings. In most of the real-world cases I've seen, those are used for tracking purposes or similar, and can mess up deduplication efforts, so it makes sense just to truncate them. But in some cases you might find that the query strings were essential to the page, so I have this in there as an option.

**Comment by thisisparker** [comment]
Closed with 83f49b2b88d50156f44ec59b29474378f41e3e49.
