### ISSUE TITLE
add a timeout for requests

### ISSUE THREAD

**Issue by jfilter** [freedomofpress/trackthenews#6]
My process hangs indefinitely and I assume it's because there are is no timeout for the requests: http://docs.python-requests.org/en/master/user/quickstart/#timeouts

Adding a timeout should fix this.

**Comment by thisisparker** [comment]
Huh, I could've sworn there was a default timeout in `requests`, but I guess that's likely [not coming until 3.0](https://github.com/requests/requests/issues/3070). I'll add one... 30 seconds seems like the right length to me, but I'm open to suggestions.

**Comment by thisisparker** [comment]
Closed with 977c678284e156605edafa627de73737c2fa27fb and pushed to PyPi, feel free to `pip install -U` for that lovely timeout experience

**Comment by jfilter** [comment]
Not really made for humans ™.

Thanks dude.
