### ISSUE TITLE
Update matchwords-sample.txt to be matchlist-sample.txt

### ISSUE THREAD

**Issue by Cauchon** [freedomofpress/trackthenews#8]
The set up process creates a file called matchlist.txt.
> A new matchlist has been generated at /home/ubuntu/trackthenews/ttnconfig/matchlist.txt.

It appears that the sample file is misnamed, it would be clearer if it was matchlist-sample.txt.

(Low Priority)

**Comment by thisisparker** [comment]
Oh yes, good catch! I went through a couple naming conventions at first but you're right that this should be moved for consitency's sake. Closed with 066d78ad0faf5d20b57322601c8e8bbee3b044df.
