### ISSUE TITLE
Bot sometimes tweets content that doesn't include matchwords

### ISSUE THREAD

**Issue by Cauchon** [freedomofpress/trackthenews#9]
I've done a bunch of debugging over the past two days and not sure why it's happening. It seems to be especially bad when a new feed is added.

Overall, it is working - but occasionally it is tweeting stories and screenshots that don't include the matchwords.

- matchwords.txt: https://gist.github.com/Cauchon/78e7e70fe03e7237a52b20c6e85d9ea1
- matchlist_case_sensitive.txt is empty

Example tweets without matchword:
- https://twitter.com/king_infosec/status/1014558990687059968
- https://twitter.com/king_infosec/status/1014305819137986560
- https://twitter.com/king_infosec/status/1014305332556804096
- https://twitter.com/king_infosec/status/1014304807597662208
- https://twitter.com/king_infosec/status/1014304330357170176
- https://twitter.com/king_infosec/status/1014284188856377345
- https://twitter.com/king_infosec/status/1014283175034359809
- https://twitter.com/king_infosec/status/1014282196708831233

**Comment by thisisparker** [comment]
Hi @Cauchon! Sorry for an annoying debugging experience. This is indeed very confusing. One thing to watch out for is that it will definitely do sub-word matches, which can be useful for matching all of the forms of a verb (or catching plurals) but it can make some matches that seem off. So for example, I would move `NSL` to the case-sensitive file, so you don't match on words like `translate` or `onslaught`. That doesn't look like it's responsible for these particular matches, but I wonder if it might help you figure out what's going on?

(BTW, the very first link does in fact match `exposed`, which seems like it might produce other out-of-context matches.)

Other than that... is the gist you posted the full list? I haven't seen this behavior before!

**Comment by Cauchon** [comment]
Yup, I think that helps narrow down the issue. Appreciate the response!
